name: Deploy .Net App to Dev, Test, and Prod Azure App Service

env:
  registryName: 6m5h7lwxxtw2ampnpreg.azurecr.io
  repositoryName: techexcel/dotnetcoreapp
  dockerFolderPath: ./src/Application/src/RazorPagesTestSample
  tag: ${{github.run_number}}

on:
  push:
    branches: [ main ]
    paths: src/Application/**
  workflow_dispatch:
jobs: 
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0
    
    - name: Restore dependencies
      run: dotnet restore ./src/Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build --no-restore ./src/Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj

  dockerBuildPush:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      uses: docker/login-action@v1.9.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        # Username used to log against the Docker registry
        username: ${{ secrets.ACR_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.ACR_PASSWORD }}
        # Log out from the Docker registry at the end of a job
        logout: true
        
    - name: Docker Build
      run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath
      
    - name: Docker Push
      run: docker push $registryName/$repositoryName:$tag

  deploy-to-dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: dockerBuildPush
    environment:
      name: dev
      url: https://6m5h7lwxxtw2a-dev.azurewebsites.net/
    
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - uses: azure/webapps-deploy@v2
        with:
          app-name: '6m5h7lwxxtw2a-dev'
          images: 6m5h7lwxxtw2ampnpreg.azurecr.io/techexcel/dotnetcoreapp:${{github.run_number}}

  deploy-to-test:
  
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: deploy-to-dev
    environment:
      name: test
      url: https://6m5h7lwxxtw2a-test.azurewebsites.net/
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v2.1.1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - uses: azure/webapps-deploy@v2
      with:
        app-name: '6m5h7lwxxtw2a-test'
        images: 6m5h7lwxxtw2ampnpreg.azurecr.io/techexcel/dotnetcoreapp:${{github.run_number}}

  deploy-to-prod:
  
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: deploy-to-test
    environment:
      name: prod
      url: https://6m5h7lwxxtw2a-prod.azurewebsites.net/
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v2.1.1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - uses: azure/webapps-deploy@v2
      with:
        app-name: '6m5h7lwxxtw2a-prod'
        images: 6m5h7lwxxtw2ampnpreg.azurecr.io/techexcel/dotnetcoreapp:${{github.run_number}}
